###############################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy <ethan.twardy@gmail.com>
#
# DESCRIPTION:	    Makefile for the snmpd-conf package.
#
# CREATED:	    11/04/2022
#
# LAST EDITED:	    11/04/2022
###

build:
	: # Intentionally empty

install:
	install -Dm644 snmpd.conf $(DESTDIR)/usr/share/snmp/snmpd.conf

###############################################################################
